============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/stidsem4/iut/2021/controle/eric.han/c16_03
collected 7 items

test_16_03.py ..F....                                                    [100%]

=================================== FAILURES ===================================
_____________________________ Test1603sute.test_4 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_4>

    def test_4(self):
        try:
            from main import moyenne_tuples
        except ImportError:
            try:
                from .main import moyenne_tuple as moyenne_tuples
            except ImportError:
                assert False, "moyenne_tuples non dÃ©finie"
    
        note1 = ('elv1', 'xx', 10)
        note2 = ('elv1', 'xx', 11)
    
>       assert moyenne_tuples((note1, note2), 'elv1', 'xx') == 10.5
E       AssertionError: assert 10.0 == 10.5
E        +  where 10.0 = <function moyenne_tuple at 0x7ff210a67ca0>((('elv1', 'xx', 10), ('elv1', 'xx', 11)), 'elv1', 'xx')

test_16_03.py:26: AssertionError
=========================== short test summary info ============================
FAILED test_16_03.py::Test1603sute::test_4 - AssertionError: assert 10.0 == 10.5
========================= 1 failed, 6 passed in 0.06s ==========================
